apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gitops-foundations-hpa
  namespace: flagger-exercise
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gitops-foundations
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 99
