apiVersion: v1
kind: Service
metadata:
  name: gitops-foundations
  namespace: argocd-exercise
spec:
  type: NodePort
  selector:
    app: gitops-foundations 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
